name: QT

on:
  push:
    branches: [ "feature/actions" ]

jobs:
  build-linux:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@vč

      - name: Install dependencies
        run: |
             sudo apt-get update
             sudo apt-get install libgl1-mesa-dev libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-render-util0 libxcb-xinerama0 libzstd-dev

      - name: Compile
        run: |
             qmake MyBachelor.pro CONFIG+=release PREFIX=/usr
             make -j8
